### ISSUE TITLE
Regarding language support

### ISSUE THREAD

**Issue by amalshaji** [amalshaji/markdown-to-medium#1]
# The Problem

The [language_map.json](https://github.com/amalshaji/markdown-to-medium/blob/master/language_map.json) is derived from the [github linguist](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml). Languages with multiple worded names(like `1C Enterprise`) are skipped. Languages with multiple extensions are mapped to the first extension. The problem arises with certain language extensions, like `Shell`.

```yaml
Shell:
  type: programming
  color: "#89e051"
  aliases:
  - sh
  - shell-script
  - bash
  - zsh
```
`Bash` is defined as an alias for the shell. However, when a `.sh` file is uploaded to github gist, the language is identified as shell, and currently, the aliases are omitted in the json file. I will rectify this soon. 

# The Solution
generate an alias map and then compare all the aliases for replacing the code blocks.
